### ISSUE TITLE
Questions about Evaluation and DAE input normalization

### ISSUE THREAD

**Issue by hojinYang** [yoongi0428/RecSys_PyTorch#1]
Hi, 

First of all, thanks for sharing this strong work! I found this repo would be really useful for researchers.

While the overall code structure is very clean and intuitive to me, I have some questions about the evaluation code. 

1. I was just wondering what `before_evaluation` methods(in Model classes) are.
2. I was wondering if your evaluation code is based on the assumption that the shape of the training matrix and test matrix are guaranteed to be the same or not. I found that the numbers of users in training and test matrices might be different as some users are dropped from the matrix in `df_to_sparse`. Does the evaluation code work even those shapes are not matched? 

3. Is there any reference about the input normalization for DAE(CDAE)? 

```
  # normalize
  user_degree = torch.norm(rating_matrix, 2, 1).view(-1, 1)   # user, 1
  item_degree = torch.norm(rating_matrix, 2, 0).view(1, -1)   # 1, item
  normalize = torch.sqrt(user_degree @ item_degree)
  zero_mask = normalize == 0
  normalize = torch.masked_fill(normalize, zero_mask.bool(), 1e-10)

  normalized_rating_matrix = rating_matrix / normalize
```

Thanks!

**Comment by yoongi0428** [comment]
Hi, thanks for your interest on this repo.

1. `before_evaluation` function is a function that is called inside `evaluator.evaluate` before the actual evaluation is done. This is a useful code for models who need pre-computations before evaluation (e.g. graph embedding in NGCF, LightGCN). If you do not implement anything, then nothing happens.
2. I agree that train users and test users can be different. In current version of codes, the shape of train / test matrix are the same. But I think users with zero test items can be filtered out using a if clause in `evaluator.prec_recall_ndcg` as below. I'll add it in the next update.
```python
...
for idx, u in enumerate(target):
  pred_u = topk[idx]
  target_u = target[u]
  num_target_items = len(target_u)
  if num_target_items < 1:
    continue
  for k in self.top_k:
    pred_k = pred_u[:k]
...
```

3. Actually, I did not realize the code is included since it was my own simple modification for fun(?). As far as I know user-side l1 normalization is applied in MultVAE official code. And user and item side l2 normalization is usually adopted in Graph Convolution Network, which is similar to symmetric normalized Laplacian matrix. It balances weights of the edges in user-item bipartite graph. Please check GCN paper for more detail.
https://arxiv.org/pdf/1609.02907.pdf

p.s. This repo is to provide playground for people who need a quickstart code for Top-N recommendation. I'm currently building a framework with more functionalities and modules (flexible preprocess, fast and various evaluation using C++) for PyTorch RecSys research field. If you are interested, please feel free to contact via e-mail.
